# Generated by Django 2.0.1 on 2018-01-24 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datarepo', '0006_remove_studentuser_courses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ('level',)},
        ),
        migrations.RemoveField(
            model_name='stream',
            name='courses',
        ),
        migrations.AddField(
            model_name='batch',
            name='level',
            field=models.IntegerField(blank=True, choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Fourth Year')], default=1),
        ),
        migrations.AddField(
            model_name='stream',
            name='level1courses',
            field=models.ManyToManyField(related_name='level1streams', to='datarepo.Course'),
        ),
        migrations.AddField(
            model_name='stream',
            name='level2courses',
            field=models.ManyToManyField(related_name='level2streams', to='datarepo.Course'),
        ),
        migrations.AddField(
            model_name='stream',
            name='level3courses',
            field=models.ManyToManyField(related_name='level3streams', to='datarepo.Course'),
        ),
        migrations.AddField(
            model_name='stream',
            name='level4courses',
            field=models.ManyToManyField(related_name='level4streams', to='datarepo.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_teaching', to='datarepo.TeacherUser'),
        ),
    ]
