# Generated by Django 2.0.1 on 2018-01-26 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datarepo', '0007_auto_20180124_0250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ('-level',)},
        ),
        migrations.AddField(
            model_name='test',
            name='passmarks',
            field=models.PositiveIntegerField(default=8, verbose_name='Pass marks'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='classplan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='datarepo.ClassPlan'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='question_file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/questions', verbose_name='Question File'),
        ),
        migrations.AlterField(
            model_name='handout',
            name='classplan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handout', to='datarepo.ClassPlan'),
        ),
    ]
