# Generated by Django 2.0.1 on 2018-01-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarepo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='possible_teachers',
        ),
        migrations.RemoveField(
            model_name='course',
            name='streams',
        ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.AddField(
            model_name='stream',
            name='courses',
            field=models.ManyToManyField(related_name='streams', to='datarepo.Course'),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='courses',
            field=models.ManyToManyField(related_name='students', to='datarepo.Course'),
        ),
        migrations.AddField(
            model_name='teacheruser',
            name='teachable_courses',
            field=models.ManyToManyField(related_name='possible_teachers', to='datarepo.Course'),
        ),
    ]
