# Generated by Django 2.0.1 on 2018-01-22 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datarepo', '0002_auto_20180122_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datarepo.TeacherUser'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='datarepo.Batch'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='stream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='datarepo.Stream'),
        ),
    ]
