# Generated by Django 2.0.1 on 2018-01-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarepo', '0003_auto_20180122_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='handout',
            name='attached_file',
            field=models.FileField(null=True, upload_to='handouts/', verbose_name='Handout Document'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='datarepo.Course'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='rollno',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
