# Generated by Django 2.0.1 on 2018-02-27 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datarepo', '0008_auto_20180126_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='question_file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/questions', verbose_name='Attached File'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='streams',
            field=models.ManyToManyField(related_name='batches', to='datarepo.Stream', verbose_name='Streams associated with the batch'),
        ),
        migrations.AlterField(
            model_name='classplan',
            name='classdate',
            field=models.DateField(verbose_name='Class Date'),
        ),
        migrations.AlterField(
            model_name='classplan',
            name='course',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='classplans', to='datarepo.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='profilepic',
            field=models.ImageField(upload_to='courses/', verbose_name='Course Picture'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_teaching', to='datarepo.TeacherUser', verbose_name='Teacher assigned'),
        ),
        migrations.AlterField(
            model_name='handout',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='level1courses',
            field=models.ManyToManyField(blank=True, related_name='level1streams', to='datarepo.Course', verbose_name='Courses taught in 1st year'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='level2courses',
            field=models.ManyToManyField(blank=True, related_name='level2streams', to='datarepo.Course', verbose_name='Courses taught in 2nd year'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='level3courses',
            field=models.ManyToManyField(blank=True, related_name='level3streams', to='datarepo.Course', verbose_name='Courses taught in 3rd year'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='level4courses',
            field=models.ManyToManyField(blank=True, related_name='level4streams', to='datarepo.Course', verbose_name='Courses taught in 4th year'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='startingrollno',
            field=models.PositiveIntegerField(unique=True, verbose_name='Starting Roll Number'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='stream_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Stream ID'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='datarepo.Batch'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='rollno',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='datarepo.Stream'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='datarepo.Assignment'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='datarepo.StudentUser'),
        ),
        migrations.AlterField(
            model_name='teacheruser',
            name='profilepic',
            field=models.ImageField(upload_to='teachers/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='teacheruser',
            name='teachable_courses',
            field=models.ManyToManyField(blank=True, related_name='possible_teachers', to='datarepo.Course'),
        ),
        migrations.AlterField(
            model_name='tempstudentuser',
            name='rollno',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='test',
            name='chapters_to_study',
            field=models.ManyToManyField(related_name='featuring_tests', to='datarepo.Chapter', verbose_name='Chapters in Syllabus'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_id',
            field=models.CharField(blank=True, max_length=300, primary_key=True, serialize=False),
        ),
    ]
